# Nodejs software
language: node_js

node_js:
  - 5.8.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
code_climate:
    repo_token: 67f8f00d5cf9e5c46b7644aebee5ac9df9d6ee267014a6f61a7a7b1048357a1c

sudo: false

# Unit Tests (+code coverage)
script: npm run-script test-travis

after_success:
  # Send coverage data to Coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -Rf ./coverage

before_deploy:
  # Download & embed Nodejs binary
  - NVER=`node -v`
  - DUNITER_VER=`git describe --exact-match --tags $(git log -n1 --pretty='%h') | grep -Po "\d.*"`
  - DUNITER_DEB_VER =" $DUNITER_VER"
  - wget http://nodejs.org/dist/${NVER}/node-${NVER}-linux-x64.tar.gz
  - tar xzf node-${NVER}-linux-x64.tar.gz
  - mv node-${NVER}-linux-x64 node
  - rm node-${NVER}-linux-x64.tar.gz
  # Clean testing packages
  - npm prune --production
  - tar czf ../ucoin-x64.tar.gz ./ --exclude ".git" --exclude "coverage" --exclude "test"
  - SRC=`pwd`
  - cd ..
  # GUI Version
  - mkdir ucoin_release
  - NW_RELEASE="v0.13.0-rc2"
  - NW="nwjs-${NW_RELEASE}-linux-x64"
  - NW_GZ="${NW}.tar.gz"
  - wget http://dl.nwjs.io/${NW_RELEASE}/${NW_GZ}
  - tar xvzf ${NW_GZ}
  - mv ${NW} ucoin_release/nw
  - cp ${SRC}/gui/* ucoin_release/nw/
  - cp -R ${SRC}/ ucoin_release/sources/
  - rm -Rf ucoin_release/sources/ui/package/node_modules
  - rm -Rf ucoin_release/sources/ui/package/bower_components
  - cd ucoin_release
  - tar czf ../duniter-x64.tar.gz * --exclude ".git" --exclude "coverage" --exclude "test"
  - cd ..
  - git clone https://github.com/ucoin-io/debpkg.git duniter-x64
  - mkdir -p duniter-x64/opt/duniter/
  - chmod 755 duniter-x64/DEBIAN/post*
  - sed -i "s/Version:.*/Version:$DUNITER_DEB_VER/g" duniter-x64/DEBIAN/control
  - cd ucoin_release/sources
  - rm -Rf .git
  - zip -qr ../duniter-desktop.nw *
  - cd ../nw
  - zip -qr ../nw.nwb *
  - cd ../..
  - rm -Rf duniter-x64/.git
  - mv ucoin_release/duniter-desktop.nw duniter-x64/opt/duniter/
  - mv ucoin_release/nw.nwb duniter-x64/opt/duniter/
  - fakeroot dpkg-deb --build duniter-x64

# Releases deployed on GitHub
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    secure: feyz5YmzYj6g6ZJKAv7u3pp9j9OY6oL4Pcx8mkha25BT1kEIu7lzvkZu4mJAIDjCxJjEkce3fNGXhRICqoMhRy/FK5dUUTpmP3KoMLNNJboO+MhDqjPEb6OYyafikSWnm0BszPL38FzSYMdmvNZ6WirOyVfrdzVPgU6MG0D99w8=
  file:
    - ucoin-x64.tar.gz
    - duniter-x64.tar.gz
    - duniter-x64.deb
  on:
    repo: ucoin-io/ucoin
    tags: true
