environment:
  matrix:
    - nodejs_version: "5.8.0"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -v
  - npm install -g npm
  - npm install

test_script:
  - npm test

build: off

before_deploy:
  - choco install -y wget 7zip
  - set PATH="C:\Program Files\7-Zip";%PATH%
  # GUI Version
  - set SRC=%cd%
  - echo %SRC%
  - cd ..
  - mkdir ucoin_release
  - set NW_RELEASE=v0.13.0-rc2
  - echo %NW_RELEASE%
  - set NW=nwjs-%NW_RELEASE%-win-x64
  - echo %NW%
  - set NW_GZ=%NW%.zip
  - echo %NW_GZ%
  - wget http://dl.nwjs.io/%NW_RELEASE%/%NW_GZ%
  - 7z x %NW_GZ%
  - move %NW% %cd%\ucoin_release\nw
  - mkdir %cd%\ucoin_release\sources
  - xcopy %SRC%\gui\* %cd%\ucoin_release\nw\ /s /e
  - xcopy %SRC%\* %cd%\ucoin_release\sources\ /s /e
  - rd /s /q %cd%\ucoin_release\sources\ui\package\node_modules
  - rd /s /q %cd%\ucoin_release\sources\ui\package\bower_components
  - rd /s /q %cd%\ucoin_release\sources\.git\
  - rd /s /q %cd%\ucoin_release\sources\test\
  - 7z a -tzip duniter-win-x64.zip %cd%\ucoin_release\*

deploy:
  release: ucoin-v$(appveyor_build_version)
  description: 'Appveyor test'
  provider: GitHub
  auth_token:
    secure: feyz5YmzYj6g6ZJKAv7u3pp9j9OY6oL4Pcx8mkha25BT1kEIu7lzvkZu4mJAIDjCxJjEkce3fNGXhRICqoMhRy/FK5dUUTpmP3KoMLNNJboO+MhDqjPEb6OYyafikSWnm0BszPL38FzSYMdmvNZ6WirOyVfrdzVPgU6MG0D99w8=
  artifact: /duniter-win-x64.zip/
  draft: true
  prerelease: false
  on:
    branch: appveyor
    appveyor_repo_tag: false